package com.oic.bookreminder.models.tables;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;
import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table BOOK.
*/
public class BookDao extends AbstractDao<Book, Long> {

    public static final String TABLENAME = "BOOK";

    /**
     * Properties of entity Book.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "ID");
        public final static Property BookId = new Property(1, String.class, "bookId", false, "BOOK_ID");
        public final static Property Title = new Property(2, String.class, "title", false, "TITLE");
        public final static Property Author = new Property(3, String.class, "author", false, "AUTHOR");
        public final static Property Isbn10 = new Property(4, String.class, "isbn10", false, "ISBN10");
        public final static Property Isbn13 = new Property(5, String.class, "isbn13", false, "ISBN13");
        public final static Property Cost = new Property(6, String.class, "cost", false, "COST");
        public final static Property TotalPages = new Property(7, Integer.class, "totalPages", false, "TOTAL_PAGES");
        public final static Property CreatedDate = new Property(8, java.util.Date.class, "createdDate", false, "CREATED_DATE");
    };


    public BookDao(DaoConfig config) {
        super(config);
    }
    
    public BookDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'BOOK' (" + //
                "'ID' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'BOOK_ID' TEXT," + // 1: bookId
                "'TITLE' TEXT," + // 2: title
                "'AUTHOR' TEXT," + // 3: author
                "'ISBN10' TEXT," + // 4: isbn10
                "'ISBN13' TEXT," + // 5: isbn13
                "'COST' TEXT," + // 6: cost
                "'TOTAL_PAGES' INTEGER," + // 7: totalPages
                "'CREATED_DATE' INTEGER);"); // 8: createdDate
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'BOOK'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Book entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String bookId = entity.getBookId();
        if (bookId != null) {
            stmt.bindString(2, bookId);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(3, title);
        }
 
        String author = entity.getAuthor();
        if (author != null) {
            stmt.bindString(4, author);
        }
 
        String isbn10 = entity.getIsbn10();
        if (isbn10 != null) {
            stmt.bindString(5, isbn10);
        }
 
        String isbn13 = entity.getIsbn13();
        if (isbn13 != null) {
            stmt.bindString(6, isbn13);
        }
 
        String cost = entity.getCost();
        if (cost != null) {
            stmt.bindString(7, cost);
        }
 
        Integer totalPages = entity.getTotalPages();
        if (totalPages != null) {
            stmt.bindLong(8, totalPages);
        }
 
        java.util.Date createdDate = entity.getCreatedDate();
        if (createdDate != null) {
            stmt.bindLong(9, createdDate.getTime());
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Book readEntity(Cursor cursor, int offset) {
        Book entity = new Book( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // bookId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // title
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // author
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // isbn10
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // isbn13
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // cost
            cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7), // totalPages
            cursor.isNull(offset + 8) ? null : new java.util.Date(cursor.getLong(offset + 8)) // createdDate
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Book entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setBookId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setTitle(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setAuthor(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setIsbn10(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setIsbn13(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setCost(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setTotalPages(cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7));
        entity.setCreatedDate(cursor.isNull(offset + 8) ? null : new java.util.Date(cursor.getLong(offset + 8)));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Book entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Book entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
