package com.oic.bookreminder.models.tables;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table NOTE.
 */
public class note {

    private Long id;
    private long bookId;
    private String content;
    private java.util.Date createdDate;
    private Boolean complete;
    private Boolean isReading;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public note() {
    }

    public note(Long id) {
        this.id = id;
    }

    public note(Long id, long bookId, String content, java.util.Date createdDate, Boolean complete, Boolean isReading) {
        this.id = id;
        this.bookId = bookId;
        this.content = content;
        this.createdDate = createdDate;
        this.complete = complete;
        this.isReading = isReading;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getBookId() {
        return bookId;
    }

    public void setBookId(long bookId) {
        this.bookId = bookId;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public java.util.Date getCreatedDate() {
        return createdDate;
    }

    public void setCreatedDate(java.util.Date createdDate) {
        this.createdDate = createdDate;
    }

    public Boolean getComplete() {
        return complete;
    }

    public void setComplete(Boolean complete) {
        this.complete = complete;
    }

    public Boolean getIsReading() {
        return isReading;
    }

    public void setIsReading(Boolean isReading) {
        this.isReading = isReading;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
