package com.oic.bookreminder.models.tables;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table READ.
 */
public class Read {

    private Long id;
    private long bookId;
    private Integer page;
    private String content;
    private java.util.Date createdDate;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Read() {
    }

    public Read(Long id) {
        this.id = id;
    }

    public Read(Long id, long bookId, Integer page, String content, java.util.Date createdDate) {
        this.id = id;
        this.bookId = bookId;
        this.page = page;
        this.content = content;
        this.createdDate = createdDate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getBookId() {
        return bookId;
    }

    public void setBookId(long bookId) {
        this.bookId = bookId;
    }

    public Integer getPage() {
        return page;
    }

    public void setPage(Integer page) {
        this.page = page;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public java.util.Date getCreatedDate() {
        return createdDate;
    }

    public void setCreatedDate(java.util.Date createdDate) {
        this.createdDate = createdDate;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
