package com.oic.bookreminder.models.tables;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table USER.
 */
public class User {

    private Long id;
    private Long userId;
    private String accessToken;
    private String gcmToken;
    private String displayName;
    private String fbId;
    private String fbAccessToken;
    private Long fbExpiredDate;
    private String fbEmail;
    private String fbUserName;
    private String privateEmail;
    private String avatarUrl;
    private Boolean isActivated;
    private Integer emailNotification;
    private String language;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public User() {
    }

    public User(Long id) {
        this.id = id;
    }

    public User(Long id, Long userId, String accessToken, String gcmToken, String displayName, String fbId, String fbAccessToken, Long fbExpiredDate, String fbEmail, String fbUserName, String privateEmail, String avatarUrl, Boolean isActivated, Integer emailNotification, String language) {
        this.id = id;
        this.userId = userId;
        this.accessToken = accessToken;
        this.gcmToken = gcmToken;
        this.displayName = displayName;
        this.fbId = fbId;
        this.fbAccessToken = fbAccessToken;
        this.fbExpiredDate = fbExpiredDate;
        this.fbEmail = fbEmail;
        this.fbUserName = fbUserName;
        this.privateEmail = privateEmail;
        this.avatarUrl = avatarUrl;
        this.isActivated = isActivated;
        this.emailNotification = emailNotification;
        this.language = language;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public String getAccessToken() {
        return accessToken;
    }

    public void setAccessToken(String accessToken) {
        this.accessToken = accessToken;
    }

    public String getGcmToken() {
        return gcmToken;
    }

    public void setGcmToken(String gcmToken) {
        this.gcmToken = gcmToken;
    }

    public String getDisplayName() {
        return displayName;
    }

    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    public String getFbId() {
        return fbId;
    }

    public void setFbId(String fbId) {
        this.fbId = fbId;
    }

    public String getFbAccessToken() {
        return fbAccessToken;
    }

    public void setFbAccessToken(String fbAccessToken) {
        this.fbAccessToken = fbAccessToken;
    }

    public Long getFbExpiredDate() {
        return fbExpiredDate;
    }

    public void setFbExpiredDate(Long fbExpiredDate) {
        this.fbExpiredDate = fbExpiredDate;
    }

    public String getFbEmail() {
        return fbEmail;
    }

    public void setFbEmail(String fbEmail) {
        this.fbEmail = fbEmail;
    }

    public String getFbUserName() {
        return fbUserName;
    }

    public void setFbUserName(String fbUserName) {
        this.fbUserName = fbUserName;
    }

    public String getPrivateEmail() {
        return privateEmail;
    }

    public void setPrivateEmail(String privateEmail) {
        this.privateEmail = privateEmail;
    }

    public String getAvatarUrl() {
        return avatarUrl;
    }

    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl;
    }

    public Boolean getIsActivated() {
        return isActivated;
    }

    public void setIsActivated(Boolean isActivated) {
        this.isActivated = isActivated;
    }

    public Integer getEmailNotification() {
        return emailNotification;
    }

    public void setEmailNotification(Integer emailNotification) {
        this.emailNotification = emailNotification;
    }

    public String getLanguage() {
        return language;
    }

    public void setLanguage(String language) {
        this.language = language;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
