package com.oic.bookreminder.models.tables;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table USER_BOOK.
 */
public class UserBook {

    private Long id;
    private Long userId;
    private Long bookId;
    private Integer quantity;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public UserBook() {
    }

    public UserBook(Long id) {
        this.id = id;
    }

    public UserBook(Long id, Long userId, Long bookId, Integer quantity) {
        this.id = id;
        this.userId = userId;
        this.bookId = bookId;
        this.quantity = quantity;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Long getBookId() {
        return bookId;
    }

    public void setBookId(Long bookId) {
        this.bookId = bookId;
    }

    public Integer getQuantity() {
        return quantity;
    }

    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
