package com.oic.bookreminder.models.tables;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table USER_BOOK.
 */
public class UserBook {

    private Long id;
    private String userId;
    private String bookId;
    private String quantity;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public UserBook() {
    }

    public UserBook(Long id) {
        this.id = id;
    }

    public UserBook(Long id, String userId, String bookId, String quantity) {
        this.id = id;
        this.userId = userId;
        this.bookId = bookId;
        this.quantity = quantity;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getBookId() {
        return bookId;
    }

    public void setBookId(String bookId) {
        this.bookId = bookId;
    }

    public String getQuantity() {
        return quantity;
    }

    public void setQuantity(String quantity) {
        this.quantity = quantity;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
