package com.oic.bookreminder.models.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.oic.bookreminder.models.greendao.User;
import com.oic.bookreminder.models.greendao.Notification;

import com.oic.bookreminder.models.greendao.UserDao;
import com.oic.bookreminder.models.greendao.NotificationDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig notificationDaoConfig;

    private final UserDao userDao;
    private final NotificationDao notificationDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        notificationDaoConfig = daoConfigMap.get(NotificationDao.class).clone();
        notificationDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        notificationDao = new NotificationDao(notificationDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Notification.class, notificationDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        notificationDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public NotificationDao getNotificationDao() {
        return notificationDao;
    }

}
