<?php
/**
 * Created by PhpStorm.
 * User: khacpham
 * Date: 6/23/15
 * Time: 00:06
 */

class Comment_model extends CI_Model{
  private $TABLE_NAME = 'comment';

  public function get_comments($limit,$offset){
    $this->db->from($this->TABLE_NAME);
    $this->db->order_by('createdDate');
    $this->db->limit($limit, $offset);
    $query = $this->db->get();
    return $query->result_array();
  }

  public function get_bookcomments($bookId,$limit,$offset)
  {
    if (! $bookId)
    {
      return array();
    }
    $this->db->from($this->TABLE_NAME);
    $this->db->where('bookId', $bookId);
    $this->db->order_by('createdDate');
    $this->db->limit($limit, $offset);
    $query = $this->db->get();
    return $query->result_array();
  }

  public function get_comment($id){
    $q = $this->db->select('*')
      ->from($this->TABLE_NAME)
      ->where('id',$id)
      ->get();
    return $q->row();
  }

  public function create_comment($comment){
    $data = array(
      'userId' => $comment->userId,
      'bookId' => $comment->bookId,
      'userName' => $comment->userName,
      'bookTitle' => $comment->bookTitle,
      'content' => $comment->content,
      'image' => $comment->image,
      'link' => $comment->link,
      //'createdDate' => $comment->createdDate,   // auto generated by MySql
      //'isDeleted' => 0    // auto generated by MySql
    );

    return $this->db->insert($this->TABLE_NAME, $data);
  }
}